<a href="https://colab.research.google.com/github/ishancoderr/3D_modeling/blob/main/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

# Read the CSV file
df = pd.read_excel("/content/H&M.xlsx")
df.head(10)

,retviews_style_id,retviews_refco,reference,Product_Id,first_capture,last_capture,source,country,gender,brand,...,sizes_not_available_count,outlet,excluweb,quantity,sub_labels,matching_reference,matching_url,matching_last_price,matching_full_price,matching_currency
0,1000128001_hm_us_women,1000128001_hm_us_women_black_black,1.000128e+09,1000128.0,2022-02-01,2022-04-03,H&M (us),US,Women,H&M,...,1.0,0.0,0.0,1.0,"Casual, Basic, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
1,1000128007_hm_us_women,1000128007_hm_us_women_grey_light beige,1.000128e+09,1000128.0,2022-02-01,2022-04-03,H&M (us),US,Women,H&M,...,0.0,0.0,0.0,1.0,"Casual, Basic, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
2,1000128008_hm_us_women,1000128008_hm_us_women_natural_powder beige,1.000128e+09,1000128.0,2022-02-16,2022-04-03,H&M (us),US,Women,H&M,...,0.0,0.0,0.0,1.0,"Casual, Basic, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
3,1000194001_hm_us_women,1000194001_hm_us_women_grey_white,1.000194e+09,1000194.0,2022-01-10,2022-04-03,H&M (us),US,Women,H&M,...,0.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
4,1000194002_hm_us_women,1000194002_hm_us_women_blue_light blue/striped,1.000194e+09,1000194.0,2022-01-10,2022-04-03,H&M (us),US,Women,H&M,...,0.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
5,1000247001_hm_us_women,1000247001_hm_us_women_grey_white,1.000247e+09,1000247.0,2022-01-28,2022-03-11,H&M (us),US,Women,H&M,...,5.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
6,1000247002_hm_us_women,1000247002_hm_us_women_yellow_light yellow/sun...,1.000247e+09,1000247.0,2022-01-28,2022-03-24,H&M (us),US,Women,H&M,...,5.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
7,1000415001_hm_us_women,1000415001_hm_us_women_black_black,1.000415e+09,1000415.0,2022-01-10,2022-04-04,H&M (us),US,Women,H&M,...,9.0,0.0,0.0,1.0,"Casual, Modern Classic, Brand, Women",NaN,NaN,NaN,NaN,NaN
8,1000506001_hm_us_women,1000506001_hm_us_women_pink_cerise,1.000506e+09,1000506.0,2022-01-11,2022-04-03,H&M (us),US,Women,H&M,...,5.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN
9,1000724001_hm_us_women,1000724001_hm_us_women_white_white/floral,1.000724e+09,1000724.0,2022-01-28,2022-03-31,H&M (us),US,Women,H&M,...,5.0,0.0,0.0,1.0,"Casual, Everyday Fashion, Brand, Women",NaN,NaN,NaN,NaN,NaN

In [30]:

product_ids =[1086766
]

In [31]:
print(df.columns)

Index(['retviews_style_id', 'retviews_refco', 'reference', 'Product_Id',
       'first_capture', 'last_capture', 'source', 'country', 'gender', 'brand',
       'title', 'department', 'category', 'sub_category', 'original_color',
       'color', 'fabrics', 'url', 'image', 'Image thumbnl', 'last_price',
       'full_price', 'discount_rate', 'currency', 'last_sizes_available',
       'sizes_count', 'last_sizes_not_available', 'sizes_not_available_count',
       'outlet', 'excluweb', 'quantity', 'sub_labels', 'matching_reference',
       'matching_url', 'matching_last_price', 'matching_full_price',
       'matching_currency'],
      dtype='object')

In [32]:
filtered_df = df[df["Product_Id"].isin(product_ids)]

filtered_df.to_excel("H_M_O.xlsx", index=False)

In [19]:
a=[
    "1060989",
    "1061000",
    "1061025",
    "1061029",
    "1061031",
    "1061126",
    "1061155",
    "1061165",
    "1061180",
    "1061209",
    "1061299",
    "1061320",
    "1061531",
    "1061554",
    "1061576",
    "1061580",
    "1061656",
    "1061691",
    "1061745",
    "1061813",
    "1061844",
    "1061907",
    "1062053",
    "1062152",
    "1062281",
    "1062283",
    "1062303",
    "1062378",
    "1062416",
    "1062429",
    "1062446",
    "1062453",
    "1062546",
    "1062561",
    "1062585",
    "1062619",
    "1062636",
    "1062661",
    "1062685",
    "1062747",
    "1062811",
    "1062874",
    "1063075",
    "1063108",
    "1063149",
    "1063196",
    "1063219",
    "1063532",
    "1063550",
    "1063693",
    "1063694",
    "1063745",
    "1063862",
    "1063867",
    "1063880",
    "1064045",
    "1064274",
    "1064317",
    "1064346",
    "1064347",
    "1064536",
    "1064702",
    "1064707",
    "1064724",
    "1064816",
    "1064921",
    "1064923",
    "1064930",
    "1064931",
    "1065374",
    "1065455",
    "1065459",
    "1065581",
    "1065732",
    "1065793",
    "1065825",
    "1066081",
    "1066230",
    "1066470",
    "1066634",
    "1066691",
    "1066701",
    "1066713",
    "1066718",
    "1066723",
    "1066746",
    "1066750",
    "1066753",
    "1066846",
    "1066903",
    "1066945",
    "1066986",
    "1067123",
    "1067169",
    "1067183",
    "1067187",
    "1067195",
    "1067300",
    "1067356",
    "1067365",
    "1067553",
    "1067610",
    "1067651",
    "1067653",
    "1067736",
    "1067752",
    "1067777",
    "1067885",
    "1068142",
    "1068459",
    "1068526",
    "1068743",
    "1068949",
    "1069220",
    "1069296",
    "1069728",
    "1069959",
    "1070297",
    "1070410",
    "1070534",
    "1070982",
    "1070994",
    "1071004",
    "1071131",
    "1071205",
    "1071228",
    "1071412",
    "1071497",
    "1071498",
    "1071527",
    "1071563",
    "1071948",
    "1072028",
    "1072178",
    "1072197",
    "1072260",
    "1072483",
    "1072487",
    "1072634",
    "1072739",
    "1073014",
    "1073121",
    "1073182",
    "1073444",
    "1073981",
    "1073993",
    "1074641",
    "1074743",
    "1074747",
    "1074751",
    "1074805",
    "1074869",
    "1074879",
    "1074902",
    "1074903",
    "1075715",
    "1076004",
    "1076012",
    "1076237",
    "1076295",
    "1076529",
    "1076588",
    "1076742",
    "1076985",
    "1077334",
    "1077560",
    "1078069",
    "1078457",
    "1078510",
    "1078570",
    "1078707",
    "1078787",
    "1078982",
    "1079415",
    "1079432",
    "1079475",
    "1079785",
    "1079794",
    "1080400",
    "1080499",
    "1080623",
    "1081176",
    "1081186",
    "1082211",
    "1082439",
    "1082624",
    "1082641",
    "1083137",
    "1084104",
    "1085455",
    "1086766"
]
b=[
	"1061320",
	"1061531",
	"1061554",
	"1061576",
	"1061580",
	"1061656",
	"1061691",
	"1061745",
	"1061813",
	"1061844",
	"1061907",
	"1062053",
	"1062152",
	"1062281",
	"1062283",
	"1062303",
	"1062378",
	"1062416",
	"1062429",
	"1062446",
	"1062453",
	"1062546",
	"1062561",
	"1062585",
	"1062619",
	"1062636",
	"1062661",
	"1062685",
	"1062747",
	"1062811",
	"1062874",
	"1063075",
	"1063108",
	"1063149",
	"1063196",
	"1063219",
	"1063532",
	"1063550",
	"1063693",
	"1063694",
	"1063745",
	"1063862",
	"1063867",
	"1063880",
	"1064045",
	"1064274",
	"1064317",
	"1064346",
	"1064347",
	"1064536",
	"1064702",
	"1064707",
	"1064724",
	"1064816",
	"1064921",
	"1064923",
	"1064930",
	"1064931",
	"1065374",
	"1065455",
	"1065459",
	"1065581",
	"1065732",
	"1065793",
	"1065825",
	"1066081",
	"1066230",
	"1066470",
	"1066634",
	"1066691",
	"1066701",
	"1066713",
	"1066718",
	"1066723",
	"1066746",
	"1066750",
	"1066753",
	"1066846",
	"1066903",
	"1066945",
	"1066986",
	"1067123",
	"1067169",
	"1067183",
	"1067187",
	"1067195",
	"1067300",
	"1067356",
	"1067365",
	"1067553",
	"1067610",
	"1067651",
	"1067653",
	"1067736",
	"1067752",
	"1067777",
	"1067885",
	"1068142",
	"1068459",
	"1068526",
	"1068743",
	"1068949",
	"1069220",
	"1069296",
	"1069728",
	"1069959",
	"1070297",
	"1070410",
	"1070534",
	"1070982",
	"1070994",
	"1071004",
	"1071131",
	"1071205",
	"1071228",
	"1071412",
	"1071497",
	"1071498",
	"1071527",
	"1071563",
	"1071948",
	"1072028",
	"1072178",
	"1072197",
	"1072260",
	"1072483",
	"1072487",
	"1072634",
	"1072739",
	"1073014",
	"1073121",
	"1073182",
	"1073444",
	"1073981",
	"1073993",
	"1074641",
	"1074743",
	"1074747",
	"1074751",
	"1074805",
	"1074869",
	"1074879",
	"1074902",
	"1074903",
	"1075715",
	"1076004",
	"1076012",
	"1076237",
	"1076295",
	"1076529",
	"1076588",
	"1076742",
	"1076985",
	"1077334",
	"1077560",
	"1078069",
	"1078457",
	"1078510",
	"1078570",
	"1078707",
	"1078787",
	"1078982",
	"1079415",
	"1079432",
	"1079475",
	"1079785",
	"1079794",
	"1080400",
	"1080499",
	"1080623",
	"1081176",
	"1081186",
	"1082211",
	"1082439"
]


# Convert the arrays to sets
set_a = set(a)
set_b = set(b)

# Calculate the differences
difference_a = set_a - set_b
difference_b = set_b - set_a

# Print the differences
print("Elements in a but not in b:", difference_a)
print("Elements in b but not in a:", difference_b)

Elements in a but not in b: {'1083137', '1061209', '1082624', '1061000', '1086766', '1060989', '1061031', '1082641', '1061155', '1084104', '1061025', '1061165', '1061180', '1061299', '1085455', '1061126', '1061029'}
Elements in b but not in a: set()